name: 'Trying Javascript with PowerShell'
inputs:
    who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'
outputs:
    time:
        description: 'The time we greeted you'
runs:
    using: 'node8'
    main: 'index.js'